wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 30
verbose:
  desc: null
  value: 1
name:
  desc: null
  value: SiameseNetwork
architecture:
  desc: null
  value: SiameseNetwork
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714988514.0
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
